# Running keycloak with docker-compose

version: '3.7'


services:
  keycloak:
    image: keycloak:24.0.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    volumes:
      - ./keycloak-data:/opt/keycloak/data
      - ./keycloak-themes:/opt/keycloak/themes


networks:
  keycloak-network:
    driver: bridge