spring:
  application:
    name: billing-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecom-realm
          jwk-set-uri: http://localhost:8080/realms/ecom-realm/protocol/openid-connect/certs

server:
  port: 8083

eureka:
  client:
    enabled: false
#    service-url:
#      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
