spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventory-db
  h2:
    console:
      enabled: true
  cloud:
    config:
      import-check:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecom-realm
          jwk-set-uri: http://localhost:8080/realms/ecom-realm/protocol/openid-connect/certs
server:
  port: 8081

eureka:
    client:
      enabled: false


